### ISSUE TITLE
Crash in estimate_free_energies()

### ISSUE THREAD

**Issue by fsimkovic** [choderalab/simulation-health-reports#1]
Running a non-example dataset worked fine without any error messages. The iPython notebook worked fine too, except at this point the script crashes. No other error messages were reported. 

Is this a bug or an indicator that my data is incorrect/incomplete?

```
Traceback (most recent call last):
  File "/home/t701886/Downloads/simulation-health-reports-master/examples/yank/analyze2.py", line 243, in <module>
    (Deltaf_ij, dDeltaf_ij) = analyze.estimate_free_energies(ncfile, ndiscard=nequil, g=g)
 File "/home/t701886/Downloads/simulation-health-reports-master/examples/yank/analyze.py", line 731, in estimate_free_energies
    (Deltaf_ij, dDeltaf_ij) = mbar.getFreeEnergyDifferences(uncertainty_method='svd-ew')
  File "/home/t701886/Downloads/simulation-health-reports-master/examples/yank/pymbar.py", line 837, in getFreeEnergyDifferences
    Theta_ij = self._computeAsymptoticCovarianceMatrix(numpy.exp(self.Log_W_nk), self.N_k, method=uncertainty_method)    
  File "/home/t701886/Downloads/simulation-health-reports-master/examples/yank/pymbar.py", line 1855, in _computeAsymptoticCovarianceMatrix
    raise ParameterError('Warning: Should have \sum_k N_k W_nk = 1.  Actual sum of row %d was %f' % (n, row_sum))      
pymbar.ParameterError: Warning: Should have \sum_k N_k W_nk = 1.  Actual sum of row 0 was 0.000000
```

**Comment by jchodera** [comment]
Thanks for the report!

Can you let me know which version of pymbar you are using?

**Comment by fsimkovic** [comment]
Please find the information below.

```
pymbar 3.0.0.beta2 np19py34_1
-----------------------------
file name   : pymbar-3.0.0.beta2-np19py34_1.tar.bz2
name        : pymbar
version     : 3.0.0.beta2
build number: 1
build string: np19py34_1
channel     : omnia
size        : 106 KB
arch        : x86_64
```

**Comment by jchodera** [comment]
Try installing `pymbar==2.1beta0` with

```
conda install --yes pymbar==2.1beta0
```

and see if that fixes the issue.  If not, there may be something wrong with the data or energies read.

**Comment by fsimkovic** [comment]
That has resolved the issue.

**Comment by jchodera** [comment]
Great, thanks! 

Any chance you would be able to share the dataset that caused the problem?  We'd love to collect some datasets that help us debug these issues with `pymbar 3.0`.  If it's proprietary, no worries, but if it was just an example or public molecule, we would very much appreciate the debugging datasets!

**Comment by fsimkovic** [comment]
Unfortunately, I cannot share the dataset.

I will try and reproduce it with one of your examples to make the debugging process easier.

**Comment by jchodera** [comment]
Don't worry about it---we'll be working through the examples shortly anyway as we upgrade to the new YAML-based syntax.  Thanks for the report!
